/**
 * Renders an animation of the distribution of the values generated by
 * `random()`.
 */

// Stores the number of times any value in the range
// [0, (randomCounts.length - 1)] was created.
int[] randomCounts;

void setup(){
	size(640, 240);
	randomCounts = new int[20];
}

void draw(){
	point(30, 30);
	int index = int(random(randomCounts.length));
	randomCounts[index]++;

	stroke(0);
	fill(175);
	int rectWidth = width / randomCounts.length;
	for(int ind = 0; ind < randomCounts.length; ind++){
		rect(
			ind * rectWidth, height - randomCounts[ind],
			rectWidth - 4, randomCounts[ind]
		);
	}
}
